# Default values for resource-manifest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Group by kubernetes kind (eg. deployment, service)
deployment:
  progressDeadlineSeconds: 150
  rollingUpdate:
    maxUnavailable: 1 #number of pods are down during update TODO
    maxSurge: 1 #number of pods are created above the desired number of pods TODO
  image: ""
  port: ""
  env: ""
  resources: ""

service:
  type: ClusterIP
  port: 80

virtualService:
  http:
    - uriPrefix: ""
      rewrite: ""
      routeDestination: ""

horizontalPodAutoscaler:
  autoscaleMax: 1
  autoscaleMin: 1
  cpu:
    targetAverageUtilization: 70
  memory:
    targetAverageUtilization: 70
