{{- if .Values.horizontalPodAutoscaler.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "resource-manifest.fullname" . }}
spec:
  maxReplicas: {{ .Values.horizontalPodAutoscaler.autoscaleMax }}
  minReplicas: {{ .Values.horizontalPodAutoscaler.autoscaleMin }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizontalPodAutoscaler.cpu.targetAverageUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizontalPodAutoscaler.memory.targetAverageUtilization }}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ include "resource-manifest.fullname" . }}
{{- end }}
