apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource-manifest.fullname" . }}
  namespace: {{ .Values.namespace | default $.Release.Namespace }}
  labels:
     {{- include "resource-manifest.labels" . | nindent 4 }}
    # deployment: {{ include "resource-manifest.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
       {{- include "resource-manifest.selectorLabels" . | nindent 6 }}
      # pod: {{ include "resource-manifest.fullname" . }}
  minReadySeconds: 15
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 #number of pods are down during update
      maxSurge: 1 #number of pods are created above the desired number of pods
  template:
    metadata:
      labels:
        {{- include "resource-manifest.selectorLabels" . | nindent 8 }}
        # pod: {{ include "resource-manifest.fullname" . }}
        app: {{ include "resource-manifest.fullname" . }}
        version: v1
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: Always
          name: {{ include "resource-manifest.fullname" . }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.env }}
          ports:
            - containerPort: {{ .Values.port }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
