apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource-manifest.fullname" . }}
  namespace: {{ .Values.deployment.namespace | default $.Release.Namespace }}
  labels:
     {{- include "resource-manifest.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
       {{- include "resource-manifest.selectorLabels" . | nindent 6 }}
  minReadySeconds: 15
  progressDeadlineSeconds: {{ .Values.deployment.progressDeadlineSeconds }}
  strategy:
    type: RollingUpdate
    {{- if .Values.deployment.rollingUpdate }}
    rollingUpdate:  {{ toYaml .Values.deployment.rollingUpdate | nindent 6 }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "resource-manifest.selectorLabels" . | nindent 8 }}
        app: {{ include "resource-manifest.fullname" . }}
        version: v1
    spec:
      containers:
        - image: {{ .Values.deployment.image }}
          imagePullPolicy: Always
          name: {{ include "resource-manifest.fullname" . }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.deployment.env }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
          {{- if .Values.deployment.resources }}
          resources: {{ toYaml .Values.deployment.resources | nindent 12 }}
          {{- end }}
