apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "resource-manifest.fullname" . }}
spec:
  host: {{ include "resource-manifest.fullname" . }}
  subsets:
    - name: v1
      labels:
        version: v1
  # - name: v1b
  #   labels:
  #     version: v1b
