apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource-manifest.fullname" . }}
  labels:
    {{- include "resource-manifest.labels" . | nindent 4 }}
    # service: {{ include "resource-manifest.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "resource-manifest.selectorLabels" . | nindent 4 }}
    # pod: {{ include "resource-manifest.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
